# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Poker-Omaha-Hutchison
version:      1.04
version_from: lib/Games/Poker/Omaha/Hutchison.pm
installdirs:  site
requires:
    List::Util:                    0
    Object::Attribute::Cached:     0
    Test::More:                    0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
